pipeline {
    agent {
      node {
        // spin up a pod to run this build on
        label 'docker'
      }
    }
    options {
        timeout(time: 45, unit: 'MINUTES')
    }
    environment {
        REF_TAG = sh(returnStdout: true, script: "git describe --exact-match --tags $env.GIT_COMMIT || echo noTagMatches").trim()
        REF_TAG_COMMIT = sh(returnStdout: true, script: "git tag --points-at $env.GIT_COMMIT --sort taggerdate | tail -1").trim()
    }
    stages {
        stage('Preamble') {
            steps {
                echo "COMMIT: ${env.GIT_COMMIT}"
                echo "REF TAG: ${env.REF_TAG}"
                echo "REF TAG COMMIT: ${env.REF_TAG_COMMIT}"
            }
        }
        stage('Build docker image') {
            steps {
                echo 'mock build step'
            }
        }
        stage('Tag and deploy QAS') {
            steps {
                echo 'mock tag and deploy QAS'
            }
        }
        stage('Tag and deploy PRD') {
            when {
                expression { env.REF_TAG != "noTagMatches" }
            }
            steps {
                echo 'mock tag and deploy PRD'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}